# Generated by Django 5.0.2 on 2024-04-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField()),
                ('academia', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='media')),
                ('url_certificated', models.URLField(blank=True, max_length=500, null=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Developer.developer')),
            ],
        ),
    ]
