# Generated by Django 5.0.2 on 2024-04-06 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Developer', '0001_initial'),
        ('Skill', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageOfProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media')),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('imagen', models.ImageField(null=True, upload_to='media')),
                ('url_portada', models.URLField(blank=True, max_length=500, null=True)),
                ('url_proyecto', models.URLField(blank=True, null=True)),
                ('descripcionPortada', models.TextField()),
                ('detalles', models.TextField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Developer.developer')),
                ('imagenesSlider', models.ManyToManyField(to='Project.imageofproject')),
                ('skills', models.ManyToManyField(to='Skill.skill')),
            ],
        ),
    ]
