# Generated by Django 5.0.2 on 2024-04-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImagesOfProject', '0001_initial'),
        ('Project', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageOfProject',
        ),
        migrations.AlterField(
            model_name='project',
            name='imagenesSlider',
            field=models.ManyToManyField(to='ImagesOfProject.imageofproject'),
        ),
    ]
